require 'rake/clean'
require 'rake/testtask'

task :default => :test

Rake::TestTask.new(:test) do |t|
  t.test_files = FileList['*_test.rb']
  t.warning = true
end

task :ruby_version do
  puts RUBY_VERSION
end
