require 'rubygems'
require 'rspec/core/rake_task'

task :default => "spec:rcov"

namespace :spec do
  desc "Run all examples using rcov"
  RSpec::Core::RakeTask.new :rcov do |t|
    t.pattern = '*_spec.rb'
  end
end
