#!/usr/bin/ruby -wKU

source 'http://rubygems.org'

gem 'rails', '3.2.3'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3-ruby', '1.3.3', :require => 'sqlite3'
gem 'basic_assumption', '0.5.1', :require => ['basic_assumption', 'basic_assumption/rails']
gem 'acts_as_list', '0.1.6'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
  gem 'rspec-rails', '2.10.1'
  gem 'rspec-collection', '2.0.0'
  gem 'flexmock', '0.9.0', :require => nil
  gem 'factory_girl', '3.2.0'
  gem 'faker', '1.0.1'
  gem 'webrat', '0.7.3'
  gem 'capybara', '1.1.2'
  gem 'database_cleaner', '0.7.2'
  gem 'cucumber', '1.1.9'
  gem 'cucumber-rails', '1.3.0'
  gem 'cover_me', '1.2.0'
  gem 'rspec-given', '1.4.2'
end

