require 'rubygems'
require 'rspec/core/rake_task'

task :default => "spec:rcov"

namespace :spec do
  desc "Run all examples using rcov"
  RSpec::Core::RakeTask.new :rcov do |t|
    t.pattern = '*_spec.rb'
    t.rcov = true
    t.rcov_opts =  %[-Ilib -Ispec --exclude "gems/*,features"]
    t.rcov_opts << %[--text-report --sort coverage --no-html --aggregate coverage.data]
  end
end
