#!/usr/bin/ruby -wKU

source 'http://rubygems.org'

gem 'rails', '3.2.3'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'acts_as_list', '0.1.6'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platform => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
  gem 'rspec-rails', '2.10.1'
  gem 'rspec-collection', '2.0.0'
  gem 'flexmock', '0.9.0', :require => nil
  gem 'factory_girl', '3.2.0'
  gem 'faker', '1.0.1'
  gem 'webrat', '0.7.3'
  gem 'capybara', '1.1.2'
  gem 'launchy'
  gem 'database_cleaner', '0.7.2'
  gem 'cucumber', '1.1.9'
  gem 'cucumber-rails', '1.3.0'
  gem 'simplecov', :require => false
  gem 'rspec-given', '1.4.2'
  gem 'pry'
end

